name: craftr-build
version: 0.0.0
author: Niklas Rosenstein <rosensteinniklas@gmail.com>
modulename: craftr.build
description: Package description here.
requirements:
- python ^3.9
entrypoints:
  craftr.plugins:
  - cxx = craftr.build.plugins.cxx
  - run = craftr.build.plugins.run
  - processor = craftr.build.plugins.processor
  console_scripts:
  - craftr = craftr.build.main:main
typed: true
