name: craftr-build
version: 5.0.0
author: Niklas Rosenstein <rosensteinniklas@gmail.com>
modulename: craftr.build
description: CLI and DSL frontend for the Craftr build system.
typed: true
requirements:
- craftr-core ~0.1.0
- craftr-dsl ~0.2.0
- python ^3.8
entrypoints:
  craftr.plugins:
  - cxx = craftr.build.plugins.cxx
  - run = craftr.build.plugins.run
  - processor = craftr.build.plugins.processor
  - haskell = craftr.build.plugins.haskell
  console_scripts:
  - craftr = craftr.build.main:main
