name: craftr-core
version: 0.0.0
author: Niklas Rosenstein <rosensteinniklas@gmail.com>
modulename: craftr.core
description: The pure Python API for describing and executing builds with Craftr.
requirements:
- python ^3.9
- nr.caching ^0.3.2
typed: true
